### ISSUE TITLE
Nerf spider spawn

### ISSUE THREAD

**Issue by ItsJay-05** [ItsBrendo/the-nuclear-wasteland#16]
Nerf it by like Half so i dont have an army of spiders on my house all day

**Comment by ItsBrendo** [comment]
Was thinking the same thing, Should be able to do it this update or next. Thanks jay.

**Comment by ItsBrendo** [comment]
I have nerfed both the spider and zombies, They will no longer spawn if there is 10 of them agro'd on one person. The more players however, The more monsters.
