### ISSUE TITLE
rats

### ISSUE THREAD

**Issue by ItsJay-05** [ItsBrendo/the-nuclear-wasteland#17]
Maybe nerf rat damage coz they're a pain in the ass :)

**Comment by ItsBrendo** [comment]
Will nerf it a little bit so instead of biting your leg off they will just bite your toe 👍

**Comment by ItsBrendo** [comment]
Might not be able to change the damage of the rats, However if you light up the area enough they shouldn't spawn, I'll close this for now, But If I find away to modify the damage later, I will re-open it.
