### ISSUE TITLE
Mod Recomendations

### ISSUE THREAD

**Issue by Wolfven** [ItsBrendo/the-nuclear-wasteland#18]
1. https://www.curseforge.com/minecraft/mc-mods/immersive-cables
2. https://www.curseforge.com/minecraft/mc-mods/ae2-stuff
3. https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum
4. https://www.curseforge.com/minecraft/mc-mods/just-enough-petroleum
5. https://www.curseforge.com/minecraft/mc-mods/immersiveposts

**Comment by ItsBrendo** [comment]
I believe these are all pretty suitable for the modpack and will see an addition in the next update! Thankyou!
