### ISSUE TITLE
conflicting recipe nails/iron bars

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#24]
the nails and the iron bars recipie is conflicting, making them uncraftable for barbed wire etc 
http://prntscr.com/uennt0
http://prntscr.com/uennwg
possible fix, change nails to require 3 vertical iron ingots

**Comment by ItsBrendo** [comment]
Ill change the Iron Bar recipe to 3 Iron Ingots in a diagonal line, I think that'd be better.

**Comment by ItsBrendo** [comment]
Iron Rods now require 3 iron in a diagonal pattern but make 6 rods
