### ISSUE TITLE
unavailable items in world

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#25]
cactus is not available in world, but is needed for BC waterproof pipes, IE hv insulators, multiple foods, etc

possible solution: add cactus to either dead grass, or desert grass drops, alternatively add as a farming villager trade

a similar issue exists with rabbit hides, but rabbits dont spawn in wasteland biome

possible solution add craftweaker recipe 2 rat pelts = 1 rabbit pelt (similar to this existing one for leather http://prntscr.com/ug4bzq ) alternative recipe: 1 leather - 2 rabbit pelts

**Comment by ItsBrendo** [comment]
I'll look into some recipe changes, in the current update you can still make waterproof pipes. Just use slime instead.

**Comment by ItsBrendo** [comment]
Cactus is now a villager trade, Might also be added to the wasteland in the next update as well, Rabbits will be in the wasteland next update too.
