### ISSUE TITLE
mod suggestion

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#26]
id like to suggest adding forestry to the pack for simple farm multiblock automation (alternative to the single item cloche). 
in addition to the multiblock farm structures, bee's and tree's are an effective content/timesink early/midgame and allow for additional building options for people willing to put in all the time required

the various overworld hives would need to be added to the bee villagers trades to be available, but the nether and end hives would be fine
additionally gendustry would be required to allow to mutate bees to be able to survive/produce in the wasteland,

**Comment by ItsBrendo** [comment]
This one might be a tough one to implement / work in the modpack. I'll have it as a suggestion for now, But not sure 100% yet.

**Comment by ItsBrendo** [comment]
What benefits do the bees add to the pack if added?

**Comment by ItsJay-05** [comment]
new consumables and farming
