### ISSUE TITLE
mod suggestion

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#27]
id also like to suggest steves carts, a way to automate farming both crops and tree's, requiring upkeep to continue running so its not a set it and forget it farm

**Comment by ItsBrendo** [comment]
How exactly does steve carts work? There is no documentation that I can find on it.

**Comment by thejiji** [comment]
basicly you build a cart with multiple components that each have their own crafting recipies, costs etc, and combine them in a cart maker (which can take several hours) heres a quide for a basic treefarm with it https://www.youtube.com/watch?v=B253G_fLN4Y

**Comment by ItsBrendo** [comment]
Yeah, not sure if this will be in the pack yet, Might look at a variant of it, but for now it won't probably be in the pack.
