### ISSUE TITLE
compatible

### ISSUE THREAD

**Issue by nkwrovnsovnsionvofsvn** [ItsBrendo/the-nuclear-wasteland#29]
Please make nuclear wasteland compatible for 3000mb

**Comment by ItsBrendo** [comment]
What do you mean sorry?

**Comment by ItsBrendo** [comment]
If you mean ram allocation, Then you should be able to do that via the Twitch Launcher (Curse Launcher). If you need more help, Please let me know 👍

**Comment by nkwrovnsovnsionvofsvn** [comment]
I use T-Launcher bro
and my mean is Nuclear wasteland run in 2600mb

**Comment by ItsBrendo** [comment]
Check your profile settings for the modpack then mate. There is an option to assign extra memory to the pack. 

Small guide:

Profile Options > Memory Settings > Uncheck "use system settings" > Set dedicated amount.

**Comment by nkwrovnsovnsionvofsvn** [comment]
Did you understand my problem?

**Comment by ItsBrendo** [comment]
If It wasn't allocating more ram, Than I'm afraid not, Mind explaining more?

**Comment by nkwrovnsovnsionvofsvn** [comment]
System.out.println(make it more compatible for older PCs);

**Comment by nkwrovnsovnsionvofsvn** [comment]
In simple words i am just saying make nuclear wasteland more efficient and
more compatible

**Comment by ItsBrendo** [comment]
...and how do you propose I do that? Update your java and allocate more memory..

**Comment by nkwrovnsovnsionvofsvn** [comment]
From which country you are?

**Comment by nkwrovnsovnsionvofsvn** [comment]
your mod is working in my computer it's a good mod and i like it
i am just saying improve more the mod

**Comment by ItsBrendo** [comment]
Australia, the modpack optimization is fine, I get 500+ fps.

**Comment by nkwrovnsovnsionvofsvn** [comment]
Awesome, thanks!
😀😀😀😀

**Comment by nkwrovnsovnsionvofsvn** [comment]
hello?
