### ISSUE TITLE
Minor Suggestion for quests

### ISSUE THREAD

**Issue by DefaultUser101** [ItsBrendo/the-nuclear-wasteland#31]
I'll be suggesting a few quests, since, currently as it stands, they're very few quests. (And yes, i do know that you, Brendo is working on other quests)

0.5 - "Trust me, i am a doctor!"; Consume any food that gives you radiation resistence. Reward: 1 XP

1 - "Long live the king!"; Completly negate the effects of radiation poisining by eating Golden apples, Golden carrots or by consuming a Rad-away/Slow Acting Rad-away. Rewards: 1 Radiation Badge and 2 Rad-away bags.

2 - "Repopulation"; Breed a pair of chickens. Rewards: 1 XP and a few seeds.

3 - "Sugary Grounds"; Find some sugar cane by cutting some grass. Rewards: 1 XP

4 - "Pointy Bussines"; Get 16 Arrows and a Bow. Reward: (X)

5 -  "Life find a way..."; Acquire 1 (Alive) Oak Sapling. Rewards: 1XP and 16 Bone Meal 

6 - "Finally, some good (fucking) food."; Collect 4 Monster Jerkeys by placing Rotten Flesh in Drying Racks. Rewards: 1 XP

7 - "No man's land."; Find 8 unlucky adventures. (Find the 8 skulls in stone pillars) Rewards: 1 Flower Bundle.

8 - "The Good, The Bad and You..." Craft a Revolver" Rewards: 1 XP

**Comment by ItsBrendo** [comment]
These are pretty awesome mate, I'll get these added when I get the chance!
