### ISSUE TITLE
mekanism solar arrays are needed for thermal evaporation plant multiblock

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#36]
like title says, see: https://ftbwiki.org/Thermal_Evaporation_Plant

**Comment by ItsBrendo** [comment]
I can't find anything on the Mekanism Solar Array.. Doesn't even appear to be a block..

**Comment by ItsBrendo** [comment]
Do you mean this? https://ftbwiki.org/Advanced_Solar_Generator

**Comment by thejiji** [comment]
yes sorry, by arrays i ment theres 2 of them , a basic, thats used to craft the advanced, thats needed for the thermal plant

**Comment by thejiji** [comment]
also, you lookin a lil sus there red, not gonna lie >.>

**Comment by ItsBrendo** [comment]
Yeah I couldn't find them in the JEI this morning, guess I'm sus. Send me a screenshot if you find out what mod they're from.

**Comment by thejiji** [comment]
they are from mekanism generators

**Comment by ItsBrendo** [comment]
fixed
