### ISSUE TITLE
(1.8) hostile mobs disabled in nether? (both single and multiplayer)

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#37]
as the title says, i cant get any hostile mobs to spawn at all in the nether, both on the server, and in single player, even blaze spawners spin up, but refuse to spawn anything. did the upload break the configs?

**Comment by thejiji** [comment]
did some digging, incontrols spawn json file only has this
[
  {
    "mob": ["minecraft:zombie", "minecraft:spider", "rats:rat"],
    "result": "default"
  },
  {
    "passive": true,
    "result": "default"
  },
  {
    "result": "deny"
  }
]

which blocks anything but those from spawning, pretty sure thats the cause, testing in SP

**Comment by ItsBrendo** [comment]
fixed
