### ISSUE TITLE
Title screen

### ISSUE THREAD

**Issue by M6mm1k** [ItsBrendo/the-nuclear-wasteland#38]
The title screen for me is all jagged up. only buttons i cans see are single and multiplayer, also report bug and support buttons..

**Comment by ItsBrendo** [comment]
Reinstall the modpack

**Comment by ItsBrendo** [comment]
This may occur when installing / updating the modpack.. Specifically in 0.1.9 for some reason.. Just reinstall the pack and it should resolve this issue. Please let me know if it does.
