### ISSUE TITLE
big issue in combat

### ISSUE THREAD

**Issue by blondy227** [ItsBrendo/the-nuclear-wasteland#42]
whenever the radiation decay occurs there is a pause in the hit registration for the player and they are not able to to damage to anything until it applies all of the effects

**Comment by ItsBrendo** [comment]
Can you give me an example? Perhaps a video?

**Comment by ItsBrendo** [comment]
Didn't mean to close.

**Comment by thejiji** [comment]
its a nuclear craft bug, its been around for ages, the way minecraft applies damage ticks and debuffs, it stops the player mid jump/attack etc. just like when yer in lava and trying to jump out. i dont think theres a way to fix it.
