### ISSUE TITLE
progression block

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#44]
there is currently a progression block with squid ink (squids dont spawn in wasteland biome)  it is heavily needed for thaumcraft as well as bibliocraft

possible fix: add a crafttweaker recipie to craft squid ink from bucket of water + pulverized coal, add as a drop to existing mob that spawns in wasteland, add a villager trade for it

**Comment by ItsBrendo** [comment]
Thanks again, jiji.

**Comment by ItsBrendo** [comment]
Added in 0.2.1
