### ISSUE TITLE
enderdragon issues

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#45]
enderdragon frequently spawns with special mobs buffs making it unkillable even with fully upgraded awakened draconic gear

possible fix: blacklist ender dragon and chaos dragon in special mobs config. they already have scaling features in place from the mod and ramp difficulty/damage/hp/regen by number of global kills (not per player) meaning after tha first 12 or so are killed, they are already very difficult to kill without full draconic gear

**Comment by ItsBrendo** [comment]
Coming in next update 👀

**Comment by ItsBrendo** [comment]
Fixed in 0.2.1
