### ISSUE TITLE
ice and fire dragons not spawning

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#46]
ice and fire dragons currently cant spawn in the wasteland biome, the following config lines block them
`
# Dragons can only spawn in these dimensions' IDs
    I:"Whitelisted Dragon Dimensions" <
        0
     >

    # Misc Structures(Cyclops caves, Gorgon temples, etc) can only spawn in these dimensions' IDs
    I:"Whitelisted Misc. Structure Dimensions" <
        0
     >
`

**Comment by ItsBrendo** [comment]
Hmm weird, Didn't change the config file, Weird its defaulted like that.

**Comment by thejiji** [comment]
yea, its normally restricted to just the overworld, i would add both the wastelands and the nether (for even more spicyness)

**Comment by ItsBrendo** [comment]
Should be spawning in 0.2.1
