### ISSUE TITLE
Applied Integrations

### ISSUE THREAD

**Issue by mcjan2** [ItsBrendo/the-nuclear-wasteland#48]
the Energy import/export bus isnt working

**Comment by ItsBrendo** [comment]
Is this still happening?

**Comment by mcjan2** [comment]
Dont know. I try later^^

Brendo ***@***.***> schrieb am So., 25. Apr. 2021, 02:36:

**Comment by ItsBrendo** [comment]
Keep me informed, Cheers mate 👍

**Comment by mcjan2** [comment]
Its working now!^^

Brendo ***@***.***> schrieb am So., 25. Apr. 2021, 12:06:

**Comment by mcjan2** [comment]
Ok. If you break these energy im/exporter you get kicked because there is
an fatal error


mcjan_ ***@***.***> schrieb am So., 25. Apr. 2021, 17:43:

**Comment by ItsBrendo** [comment]
I'll look at this for the next update.
