### ISSUE TITLE
immersive compat issue

### ISSUE THREAD

**Issue by thejiji** [ItsBrendo/the-nuclear-wasteland#5]
immersive engineering's steel axe doesnt work with treechopper mod.

probable cause: IE doesnt register its axe under the vanilla tool category

possible fixes: 1. correctly assign the axe, 2. disable the steel tools from immersive (with tinkers they are relatively redundant) 3. contact mod author of treechopper and ask him to add support

**Comment by AusRUKASU** [comment]
People are on it now, Thanks for Reporting :)

**Comment by ItsBrendo** [comment]
The IE Steel Axe is now registered with Tree Chopper, Thanks for the report @thejiji 💯
