### ISSUE TITLE
Gui scale

### ISSUE THREAD

**Issue by lilanimal13** [ItsBrendo/the-nuclear-wasteland#56]
Hello, I'm having this weird glitch where I cant change the GUI scale in the video settings menu, I was wondering if its anything to do with the modpack or if its just a glitch?

**Comment by ItsBrendo** [comment]
Not entirely too sure sorry. Have you tried re-installing?

**Comment by lilanimal13** [comment]
Not yet, let me try that

**Comment by ItsBrendo** [comment]
Perfect, Let me know how that goes. I'll be hopefully getting an update out soon enough. Just been really busy with work.

**Comment by lilanimal13** [comment]
Still dosen't work, it does highlight the button but its like theres no other changes to the button when you click it.

**Comment by ItsBrendo** [comment]
Are you in-game or on the main menu? The main menu forces the GUI Scale but in-game you should be able to change it.

**Comment by lilanimal13** [comment]
ive tried in game and menu and it wont work

**Comment by ItsBrendo** [comment]
Do you have a screenshot of whats happening at all?

**Comment by lilanimal13** [comment]
no but i can take one

**Comment by ItsBrendo** [comment]
That'd be great if you could

**Comment by lilanimal13** [comment]
https://youtu.be/BwQQvfU8tOo

**Comment by ItsBrendo** [comment]
You're on an outdated version of the pack, Try updating here: https://www.curseforge.com/minecraft/modpacks/the-nuclear-wasteland

**Comment by lilanimal13** [comment]
Oh ok thanks

**Comment by ItsBrendo** [comment]
No worries. Let me know how that goes.

**Comment by lilanimal13** [comment]
It dosent seem to be downloading for some reason

**Comment by ItsBrendo** [comment]
Download this launcher: https://download.overwolf.com/install/Download?&PartnerId=4047 and then search for it once all setup.

**Comment by lilanimal13** [comment]
ive tried pressing the "If it doesn’t, click **here**" but it wont download

**Comment by lilanimal13** [comment]
oh thanks

**Comment by lilanimal13** [comment]
After ive got the app i just look for the mods?

**Comment by ItsBrendo** [comment]
You can click that link I first sent you again and it should open up aslong as you are signed into your minecraft / curse account.

**Comment by lilanimal13** [comment]
oh ok

**Comment by lilanimal13** [comment]
ok that seemed to work, thanks!

**Comment by ItsBrendo** [comment]
So you have the new version? Should be 0.2.2 :)

**Comment by ItsBrendo** [comment]
DM me on discord if you like as well. Im looking for a few people to test / help create the next update.
