### ISSUE TITLE
Unable to join a NW server (Recipe minecraft:wheat produces unregistered item minecraft:wheat)

### ISSUE THREAD

**Issue by Thatsmusic99** [ItsBrendo/the-nuclear-wasteland#61]
When trying to join a server with the server pack from Curseforge loaded, the client quickly "crashes" with the error message `Recipe minecraft:wheat (net.minecraft.item.crafting.ShapedRecipes@112a50a1) produces unregistered item minecraft:wheat (net.minecraft.item.Item@1c14d24d)`:

https://paste.gg/p/anonymous/d07c08d96d604ef28a1d8fe38ed3f25f

Using 0.2.5 of the modpack on both the client and server.

**Comment by ItsBrendo** [comment]
I'm currently trying to reproduce this issue and I'll get back to you some information shortly.

**Comment by ItsBrendo** [comment]
Hey there, I was unable to re-produce this issue, Could you try re-installing both the client from CurseForge using [this link](https://www.curseforge.com/minecraft/modpacks/the-nuclear-wasteland/files/3666071) and then the server using [this link](https://www.curseforge.com/minecraft/modpacks/the-nuclear-wasteland/files/3666097). Thanks!

**Comment by Thatsmusic99** [comment]
This is quite peculiar, I got it working fine on a locally hosted server (Windows 10, Java 1.8.0_301) but not two externally hosted ones (running Linux, Java 1.8.0_312). Don't think I did anything wrong in the setup, I'll poke around a bit further.

**Comment by ItsBrendo** [comment]
If it helps, I'm on Windows myself, I don't have my linux box setup at the moment to test on. Maybe use the same version of Java on linux and see if that is the issue? Otherwise I'm currently setting up the SMP and you're welcome to join that.

**Comment by Thatsmusic99** [comment]
Yeah I thought I got it right but apparently after doing some extra poking around (I assume with the libraries folder), it started working properly, I've quite honestly never seen this issue come down to that and thought it'd just be a registries issue... damn.

Cheers for the speedy feedback, glad to know it wasn't down to the modpack and just me being careless.

**Comment by ItsBrendo** [comment]
No worries bud! Enjoy the pack and happy fellow developing!
